name: Rebuild bundled assets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - name: Check out code
      uses: actions/checkout@v2
    - name: Refresh Bundled Files
      run: |
        export PATH="$PATH:/usr/local/go/bin:$HOME/go/bin"
        make ci-update-bundled-deps
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.5.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Automated content rebuild
        COMMIT_AUTHOR_EMAIL: isimluk@fedorapeople.org
        COMMIT_AUTHOR_NAME: Github Actions Automation
        PULL_REQUEST_TITLE: 'Automated build of opencontrol data'
        PULL_REQUEST_BODY: |
          Automated content re-build.
        PULL_REQUEST_BRANCH: opencontrol-build
        BRANCH_SUFFIX: short-commit-hash
    - name: Check output environment variable
      run: echo "Pull Request Number - $PULL_REQUEST_NUMBER"
